language: go
go:
- 1.9
- tip
script:
- GORACE="exitcode=1 halt_on_error=1" go test -v -coverprofile=coverage.txt -race -timeout 3m -count 3 -cpu 1,4
- go tool vet -v -all .
after_success:
  - bash <(curl -s https://codecov.io/bash)
branches:
  only:
  - master
notifications:
  irc:
    channels:
    - irc.byteirc.org#/dev/null
    template:
    - "%{repository} #%{build_number} %{branch}/%{commit}: %{author} -- %{message}
      %{build_url}"
    on_success: change
    on_failure: change
    skip_join: false
